### ISSUE TITLE
kkbox --> IP address is in unsupported region, use a VPN

### ISSUE THREAD

**Issue by doug2021** [OrfiTeam/OrpheusDL#24]
Hello! I am trying to download songs from kkbox on orpheus module, but I could not it. It shows this message: 
Note: My account is not expired, I am using kkbox webplayer normally. Could anyone help me, please? 

Traceback (most recent call last):
  File "orpheus.py", line 223, in <module>
    main()
  File "orpheus.py", line 176, in main
    module = orpheus.load_module(service_name)
  File "/content/drive/MyDrive/orpheusdl/orpheus/core.py", line 203, in load_module
    loaded_module = class_(module_controller)
  File "/content/drive/MyDrive/orpheusdl/modules/kkbox/interface.py", line 44, in __init__
    self.login(settings['email'], settings['password'])
  File "/content/drive/MyDrive/orpheusdl/modules/kkbox/interface.py", line 72, in login
    self.session.login(email, password)
  File "/content/drive/MyDrive/orpheusdl/modules/kkbox/kkapi.py", line 73, in login
    raise self.exception('IP address is in unsupported region, use a VPN')
orpheus.core.ModuleError: kkbox --> IP address is in unsupported region, use a VPN

**Comment by mexsana123** [comment]
This is a KKBox issue, not a Orpheus issue.

**Comment by doug2021** [comment]
> This is a KKBox issue, not a Orpheus issue.

Thank you for your reply, but I already solved this issue.

**Comment by Slypser** [comment]
Do you know if it is possible to configure Orpheus in Termux to download from KKBOX?  And if so, what commands should I put?

**Comment by gustavofloresjuarez** [comment]
> Do you know if it is possible to configure Orpheus in Termux to download from KKBOX? And if so, what commands should I put?

Yes

**Comment by VinzyNg** [comment]
> > This is a KKBox issue, not a Orpheus issue.
> 
> Thank you for your reply, but I already solved this issue.

How did you manage to solve this?? I am facing the same problem as well

**Comment by uhwot** [comment]
@VinzyNg @lovekanbekotori make sure the module is updated, and set the new "secret_key" in settings.json
if you still have the same error after that, it's probably just a VPN issue

**Comment by doug2021** [comment]
> > > This is a KKBox issue, not a Orpheus issue.
> > 
> > 
> > Thank you for your reply, but I already solved this issue.
> 
> How did you manage to solve this?? I am facing the same problem as well

To solve Tidal bot protection I had to wait for 2 days and trying to sign in again

**Comment by xuliefeng** [comment]
> @VinzyNg @lovekanbekotori make sure the module is updated, and set the new "secret_key" in settings.json if you still have the same error after that, it's probably just a VPN issue

Hello, where can I get the requested secret_key? I didn’t see this value in my personal center

**Comment by Dniel97** [comment]
No further activity, closing.
