### ISSUE TITLE
Advanced Settings:

### ISSUE THREAD

**Issue by ViPiMP** [OrfiTeam/OrpheusDL#25]
Hello mate,
Maybe you could explain the advanced settings, even just a bit. I already played with them and the conversation to ALAC (M4A) from flac is working. 
I just ask cause I don't want to convert my tracks to a lower quality alac as they was in flac. Because in the advanced settings, you could set a compression level for the track, also cover.

Wishing you all the best!
Happy Orpheus user. :)

**Comment by mexsana123** [comment]
You shouldn't have to worry if FLAC -> ALAC is gonna "lower" the quality. It's a lossless to lossless conversion therefore no quality should be lost. Also the compression mode is mainly for FLAC conversion to compress the file sizes, while maintaining the quality.

**Comment by fmajonei** [comment]
Hi, 

I would like to encode to aiff or wav. Is it possible to do it by changing the config file in the advanced array?. Is there any documentation about that array?. I was not able to find it googling it. 
Thanks.

**Comment by Dniel97** [comment]
> Hi,
> 
> I would like to encode to aiff or wav. Is it possible to do it by changing the config file in the advanced array?. Is there any documentation about that array?. I was not able to find it googling it. Thanks.

AIFF is not supported by OrpheusDL at all so you wouldn't get any tags or metadata. I'm also not sure why you would want to convert a FLAC file to WAV file as pretty much anything could play a FLAC file. Also conversion to WAV is not supported right now.
