### ISSUE TITLE
AIFF support

### ISSUE THREAD

**Issue by axeldelafosse** [OrfiTeam/OrpheusDL#30]
Hey -- thank you very much for your work!

Is there any specific reason why the AIFF codec isn't supported? I'd love to automatically convert from FLAC to AIFF. Happy to submit a PR if you want.

Have a nice day :)

**Comment by R3AP3** [comment]
because that would be a stupid conversion. That would just uncompress the audio and i dont really see how that should benefit archiving especially in storage terms.

**Comment by axeldelafosse** [comment]
Some audio players like the [old Pioneer CDJs do not support FLAC](https://dsokolovskiy.com/blog/all/mp3/), and WAVE cover art tags are not supported universally across OSes and DJ softwares. So it makes AIFF the best format if your goal is to own audio files supported by all DJ hardware and software.

Storage is a commodity now IMO.
