### ISSUE TITLE
Download only selected artists singles and albums

### ISSUE THREAD

**Issue by area007** [OrfiTeam/OrpheusDL#35]
Function or feature to download only the selected artist link albums and singles. At the moment it's downloading everything associated to the artist selected.

**Comment by stayupthetree** [comment]
This issue still persists

**Comment by unai-ndz** [comment]
The fix seems to be setting `return_credited_albums` to `false` in the config.
I guess it makes sense but the documentation could be improved.

**Comment by OrfiDev** [comment]
Another important thing to note is that the ignore_different_artists setting also filters all the albums by other artists for only songs that the artist you are downloading actually worked on. Sorry for not responding to this issue before, I completely forgot about it
