### ISSUE TITLE
Please help me with this Issues 

### ISSUE THREAD

**Issue by japanvip115** [OrfiTeam/OrpheusDL#37]
Traceback (most recent call last):
  File "/Users/tohongson/orpheusdl/orpheus.py", line 7, in <module>
    from orpheus.core import *
  File "/Users/tohongson/orpheusdl/orpheus/core.py", line 4, in <module>
    from orpheus.music_downloader import Downloader
  File "/Users/tohongson/orpheusdl/orpheus/music_downloader.py", line 7, in <module>
    from ffmpeg import Error
ImportError: cannot import name 'Error' from 'ffmpeg' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ffmpeg/__init__.py)

**Comment by reaitten** [comment]
`pip uninstall ffmpeg`
`pip install ffmpeg_python`

**Comment by edaznaran** [comment]
According to the [installation guide for ffmpeg-python](https://github.com/kkroening/ffmpeg-python#installing-ffmpeg) you must first install `ffmpeg` with
```
apt install ffmpeg
``` 
and then
```
pip install ffmpeg-python
```

**Comment by Dniel97** [comment]
No further activity, closing.

**Comment by afnanqasimpreesoft** [comment]
import ffmpeg# Main import
from ffmpeg.errors import FFmpegError
