### ISSUE TITLE
Potential typo on code welcome page - pip3 not pip

### ISSUE THREAD

**Issue by captaineos** [OrfiTeam/OrpheusDL#42]
In macOS, the correct terminal command for 

Install all requirements
is
pip**3** install -r requirements.txt

Homepage omits the 3

**Comment by mexsana** [comment]
While I understand the concern of a typo. `pip3` is simply an alias to differ from Python 2. You can always make it where `pip` is `pip3` by running `alias pip=pip3` in your terminal.

**Comment by OrfiDev** [comment]
@captaineos You're right, I never considered that, using python or python3 and pip or pip3 (or python/python3 -m pip for that matter) all depend on the operating system you use and how exactly you install python on the system you are running. I'll add a clarification for what command to specifically use next time I update the readme.
