### ISSUE TITLE
No modules are installed

### ISSUE THREAD

**Issue by Caramellattte** [OrfiTeam/OrpheusDL#43]
Hello, I've encountered an issue during the initial setup where it says no modules installed. I have done the prerequisite  pip install -r requirements.txt and have python 3.11 (the latest ver) installed. Is there a way to fix this issue? as i tried two times and it gives the same result, thank you!

note: python 3 is substituted with "python" only in the commands as python 3 is not recognized as a command in my cmd
![No modules are installed](https://github.com/OrfiTeam/OrpheusDL/assets/145557734/ef176863-984d-47d6-a221-6e9b01cc81be)

**Comment by OrfiDev** [comment]
@Caramellattte That is unrelated, you need to install OrpheusDL-specific modules, such as ones made by me, Dniel97 or uhwot.

**Comment by AJRXv2** [comment]
Got this problem, i did everything i searched on google and nothing yet :C

**Comment by OrfiDev** [comment]
@AJRXv2 search something like "orpheusdl-qobuz", that's what it means by module

**Comment by AJRXv2** [comment]
> @AJRXv2 search something like "orpheusdl-qobuz", that's what it means by module

Omg, I didn't realize I was installing the requirement for Tidal to work, I thought I was installing just the Tidal downloader 🤦🏻
