### ISSUE TITLE
Some tracks can't be downloaded in MQA Codec

### ISSUE THREAD

**Issue by Andrea-lyz** [OrfiTeam/OrpheusDL#50]
This is my json:
`"codecs": {
            "proprietary_codecs": true,
            "spatial_codecs": false`

`"enable_mobile": true,
            "force_non_spatial": false,
            "prefer_ac4": false,
            "fix_mqa": true`

Problem tracks : https://tidal.com/album/331653715
`=== Downloading track You’re Losing Me (From The Vault) (331653717) ===
        Artists: Taylor Swift (3557299)
        Release year: 2023
        Duration: 04m:38s
        Codec: FLAC, bitrate: 1543kbps, bit depth: 24bit, sample rate: 48.0kHz
        Downloading track file
        100%|███████████████████████████████████████████████████████████████████| 72/72 [00:02<00:00, 34.33it/s]
        Downloading artwork
        Retrieving lyrics with musixmatch
        Retrieving credits
        Tagging file
=== Track 331653717 downloaded ===`

When I try other tracks, it downloads MQA correctly, for example : https://tidal.com/album/282033424
`=== Downloading track All Of The Girls You Loved Before (282033425) ===
        Artists: Taylor Swift (3557299)
        Release year: 2023
        Duration: 03m:41s
        Codec: MQA, bit depth: 24bit, sample rate: 44.1kHz
        Downloading track file
        100%|██████████████████████████████████████████████████████████████| 40.2M/40.2M [00:00<00:00, 44.2MB/s]
        Downloading artwork
        Retrieving lyrics with musixmatch
        Retrieving credits
        Tagging file
=== Track 282033425 downloaded ===`

I also tried the Tidal-dl project and was able to correctly download the MQA code for the track(331653717).

**Comment by OrfiDev** [comment]
@Andrea-lyz you're getting a higher quality version of that track than the MQA garbage Tidal used to give, unless I'm misunderstanding things. Also wrong repository, orpheusdl-tidal is the one to ask on
